name: Installs on each operating system and runs all tests
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Python${{ matrix.python-version }}-${{ matrix.os }}-${{ matrix.extension }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: [3.8, "3.10"]
        extension: ['optimised', 'plotting']
        exclude:
          - os: windows-latest  # windows does not support jax so exclude it
            extension: 'optimised'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install all dependencies
      run: |
        python -m pip install .[${{ matrix.extension }}]
    - name: Run tests
      run: |
        python test.py ${{ matrix.extension }}
